// <auto-generated />
using System;
using CV_Projektet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV_Projektet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221228140352_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CV_Projektet.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Örebro",
                            PostalCode = 12345,
                            Street = "Storgatan 1"
                        },
                        new
                        {
                            ID = 2,
                            City = "Ystad",
                            PostalCode = 12365,
                            Street = "Drottninggatan 12"
                        },
                        new
                        {
                            ID = 3,
                            City = "Göteborg",
                            PostalCode = 16845,
                            Street = "Kungsgatan 43"
                        },
                        new
                        {
                            ID = 4,
                            City = "Gnesta",
                            PostalCode = 16845,
                            Street = "Storälven 22"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Competence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Competences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "C#"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Java"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kassavana"
                        },
                        new
                        {
                            ID = 4,
                            Name = "HLR"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("TimesViewed")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("CVs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            TimesViewed = 0,
                            UserID = "användare1id"
                        },
                        new
                        {
                            ID = 2,
                            TimesViewed = 3,
                            UserID = "användare3id"
                        },
                        new
                        {
                            ID = 3,
                            TimesViewed = 12,
                            UserID = "användare2id"
                        },
                        new
                        {
                            ID = 4,
                            TimesViewed = 55,
                            UserID = "användare4id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.CV_Competences", b =>
                {
                    b.Property<int>("CVID")
                        .HasColumnType("int");

                    b.Property<int>("CompetenceID")
                        .HasColumnType("int");

                    b.HasKey("CVID", "CompetenceID");

                    b.HasIndex("CompetenceID");

                    b.ToTable("CV_Competences");

                    b.HasData(
                        new
                        {
                            CVID = 1,
                            CompetenceID = 1
                        },
                        new
                        {
                            CVID = 1,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 3
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 4
                        },
                        new
                        {
                            CVID = 3,
                            CompetenceID = 4
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 1
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 3
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Experience", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CVID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CVID");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CVID = 1,
                            City = "Lund",
                            Description = "pratade i telefon",
                            EndDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "ICA",
                            StartDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kundtjänst",
                            Type = "Work"
                        },
                        new
                        {
                            ID = 2,
                            CVID = 1,
                            City = "Örebro",
                            Description = "Java",
                            EndDate = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2021, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Systemvetenskap",
                            Type = "Education"
                        },
                        new
                        {
                            ID = 3,
                            CVID = 1,
                            City = "Göteborg",
                            Description = "HLR-utbildning",
                            EndDate = new DateTime(2022, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Företag1",
                            StartDate = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "HLR",
                            Type = "Course"
                        },
                        new
                        {
                            ID = 4,
                            CVID = 2,
                            City = "Örebro",
                            Description = "Beskrivning blabla",
                            EndDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lärarprogrammet",
                            Type = "Education"
                        },
                        new
                        {
                            ID = 5,
                            CVID = 1,
                            City = "Örebro",
                            Description = "Java",
                            EndDate = new DateTime(2022, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Systemvetenskap",
                            Type = "Education"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.ImageModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ID = 4,
                            Name = "image (1)223847664.png",
                            Title = "Profilbild",
                            UserID = "användare1id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Receiver");

                    b.HasIndex("Sender");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2022, 12, 28, 15, 3, 51, 743, DateTimeKind.Local).AddTicks(6858),
                            Read = false,
                            Receiver = "användare2id",
                            Sender = "användare1id",
                            Text = "hejsan hoppsan"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLeaderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProjectLeaderID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2021, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projektbeskrivningen blabla",
                            Name = "Planeringsprojektet",
                            ProjectLeaderID = "användare1id"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2020, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projektbeskrivningen blabla",
                            Name = "Yogahemsideprojektet",
                            ProjectLeaderID = "användare2id"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projektbeskrivningen blabla",
                            Name = "CV-Projektet",
                            ProjectLeaderID = "användare3id"
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projektbeskrivningen blabla",
                            Name = "Mötesprojektet",
                            ProjectLeaderID = "användare4id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AdressID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AdressID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "användare1id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "e141ad3b-f985-4759-a356-86561d5e9d1d",
                            Description = "Hejaaa",
                            Email = "inga@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Inga",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Karlsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnäringa",
                            PhoneNumber = "0731111111",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "328a3269-b45a-456b-b17c-3ddc194fd293",
                            TwoFactorEnabled = false,
                            UserName = "Ingis"
                        },
                        new
                        {
                            Id = "användare2id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "22169ad2-5e5d-459d-b7a7-2d324d1d0aff",
                            Description = "Halloj",
                            Email = "gunvor@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Gunvor",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Nilsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärgunvor",
                            PhoneNumber = "0732222222",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "ce2f24e6-5555-4e94-b317-9e0844c52fc1",
                            TwoFactorEnabled = false,
                            UserName = "Gunnis"
                        },
                        new
                        {
                            Id = "användare3id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "d7a6f2aa-1495-4f42-8629-55f79a0412fe",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "Jögge@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Jörgen",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Svensson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärjörgen",
                            PhoneNumber = "0733333333",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "07a7f290-1d41-4693-a401-07965449a693",
                            TwoFactorEnabled = false,
                            UserName = "Jöggis"
                        },
                        new
                        {
                            Id = "användare4id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "5ecf979f-5e34-40c5-83f0-b511abb52706",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "stenis@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Sten",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Kallesson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärsten",
                            PhoneNumber = "0744444444",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "ad2aaf96-f7f6-407e-a020-63b3e8a09de0",
                            TwoFactorEnabled = false,
                            UserName = "Stenis"
                        },
                        new
                        {
                            Id = "användare5id",
                            AccessFailedCount = 0,
                            AdressID = 3,
                            ConcurrencyStamp = "e2f45748-e81b-477e-b8fe-2bc19b5cd068",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "kajsa@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Kajsa",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Stenbäck",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärkajsa",
                            PhoneNumber = "0751235555",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "3174b41b-cf97-4f66-bbee-25313260559e",
                            TwoFactorEnabled = false,
                            UserName = "Kajsis"
                        },
                        new
                        {
                            Id = "användare6id",
                            AccessFailedCount = 0,
                            AdressID = 4,
                            ConcurrencyStamp = "31a2f19c-f346-4b42-93c6-a17f7cf5999e",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "frida@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Frida",
                            IsActive = false,
                            IsPublic = false,
                            LastName = "Liljedahl",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärfrida",
                            PhoneNumber = "0755555555",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "2afd598f-c0c3-416a-b1c2-b0e1b03dcf5e",
                            TwoFactorEnabled = false,
                            UserName = "Fridis"
                        },
                        new
                        {
                            Id = "användare7id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "87281c16-9331-465e-a9e0-46918cdc5c0b",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "linda@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Linda",
                            IsActive = true,
                            IsPublic = false,
                            LastName = "Nordeman",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärlinda",
                            PhoneNumber = "0766666666",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "772eaf8e-46af-4092-970c-42ddb43e183f",
                            TwoFactorEnabled = false,
                            UserName = "Lindis"
                        },
                        new
                        {
                            Id = "användare8id",
                            AccessFailedCount = 0,
                            AdressID = 3,
                            ConcurrencyStamp = "3cf7f71d-f461-4490-bf27-7d5801bab37a",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "lisa@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Lisa",
                            IsActive = true,
                            IsPublic = false,
                            LastName = "Kjellgren",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärlisa",
                            PhoneNumber = "0777733333",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "46d3b30f-d6de-432d-a479-c57746b2ce1c",
                            TwoFactorEnabled = false,
                            UserName = "Lisis"
                        },
                        new
                        {
                            Id = "användare9id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "3265d9bc-e7bd-4e94-8d77-1b6d02503459",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "viktor@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Viktor",
                            IsActive = false,
                            IsPublic = false,
                            LastName = "Hemlin Gravander",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärviktor",
                            PhoneNumber = "0733333333",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2021, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "85a90edf-cd3c-4056-8227-45f33805fe3f",
                            TwoFactorEnabled = false,
                            UserName = "Vickis"
                        },
                        new
                        {
                            Id = "användare10id",
                            AccessFailedCount = 0,
                            AdressID = 4,
                            ConcurrencyStamp = "137e57f3-464a-41ca-89fb-3280df7bee74",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "ulla@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Ulla",
                            IsActive = false,
                            IsPublic = true,
                            LastName = "Ivarsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärulla",
                            PhoneNumber = "0738883333",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "a23c5b84-fe87-41ee-b3fd-06324370019c",
                            TwoFactorEnabled = false,
                            UserName = "Ullis"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.User_Projects", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("User_Projects");

                    b.HasData(
                        new
                        {
                            UserID = "användare1id",
                            ProjectID = 1
                        },
                        new
                        {
                            UserID = "användare1id",
                            ProjectID = 2
                        },
                        new
                        {
                            UserID = "användare2id",
                            ProjectID = 1
                        },
                        new
                        {
                            UserID = "användare2id",
                            ProjectID = 3
                        },
                        new
                        {
                            UserID = "användare3id",
                            ProjectID = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "User")
                        .WithOne("CV")
                        .HasForeignKey("CV_Projektet.Models.CV", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CV_Projektet.Models.CV_Competences", b =>
                {
                    b.HasOne("CV_Projektet.Models.CV", "CV")
                        .WithMany("CV_Competences")
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.Competence", "Competence")
                        .WithMany("CV_Competences")
                        .HasForeignKey("CompetenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("CV_Projektet.Models.Experience", b =>
                {
                    b.HasOne("CV_Projektet.Models.CV", "CV")
                        .WithMany("Experiences")
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");
                });

            modelBuilder.Entity("CV_Projektet.Models.ImageModel", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "user")
                        .WithOne("ImageModel")
                        .HasForeignKey("CV_Projektet.Models.ImageModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CV_Projektet.Models.Message", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "UserReceiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", "UserSender")
                        .WithMany("SentMessages")
                        .HasForeignKey("Sender")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "ProjectLeader")
                        .WithMany("LeadProjects")
                        .HasForeignKey("ProjectLeaderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectLeader");
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.HasOne("CV_Projektet.Models.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AdressID");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CV_Projektet.Models.User_Projects", b =>
                {
                    b.HasOne("CV_Projektet.Models.Project", "Project")
                        .WithMany("User_Project")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", "User")
                        .WithMany("UsersAndProjects")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CV_Projektet.Models.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CV_Projektet.Models.Competence", b =>
                {
                    b.Navigation("CV_Competences");
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.Navigation("CV_Competences");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.Navigation("User_Project");
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.Navigation("CV");

                    b.Navigation("ImageModel");

                    b.Navigation("LeadProjects");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("UsersAndProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
