// <auto-generated />
using System;
using CV_Projektet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV_Projektet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221227073209_projectcreateddate")]
    partial class projectcreateddate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CV_Projektet.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Örebro",
                            PostalCode = 12345,
                            Street = "Storgatan 1"
                        },
                        new
                        {
                            ID = 2,
                            City = "Ystad",
                            PostalCode = 12365,
                            Street = "Drottninggatan 12"
                        },
                        new
                        {
                            ID = 3,
                            City = "Göteborg",
                            PostalCode = 16845,
                            Street = "Kungsgatan 43"
                        },
                        new
                        {
                            ID = 4,
                            City = "Gnesta",
                            PostalCode = 16845,
                            Street = "Storälven 22"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Competence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Competences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "C#"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Java"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kassavana"
                        },
                        new
                        {
                            ID = 4,
                            Name = "HLR"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("TimesViewed")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("CVs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            TimesViewed = 0,
                            UserID = "användare1id"
                        },
                        new
                        {
                            ID = 2,
                            TimesViewed = 3,
                            UserID = "användare3id"
                        },
                        new
                        {
                            ID = 3,
                            TimesViewed = 12,
                            UserID = "användare2id"
                        },
                        new
                        {
                            ID = 4,
                            TimesViewed = 55,
                            UserID = "användare4id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.CV_Competences", b =>
                {
                    b.Property<int>("CVID")
                        .HasColumnType("int");

                    b.Property<int>("CompetenceID")
                        .HasColumnType("int");

                    b.HasKey("CVID", "CompetenceID");

                    b.HasIndex("CompetenceID");

                    b.ToTable("CV_Competences");

                    b.HasData(
                        new
                        {
                            CVID = 1,
                            CompetenceID = 1
                        },
                        new
                        {
                            CVID = 1,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 3
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 4
                        },
                        new
                        {
                            CVID = 3,
                            CompetenceID = 4
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 1
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 3
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Experience", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CVID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CVID");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CVID = 1,
                            City = "Lund",
                            Description = "pratade i telefon",
                            EndDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(30),
                            Place = "ICA",
                            StartDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(22),
                            Title = "Kundtjänst",
                            Type = "Work"
                        },
                        new
                        {
                            ID = 2,
                            CVID = 1,
                            City = "Örebro",
                            Description = "Java",
                            EndDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(35),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(33),
                            Title = "Systemvetenskap",
                            Type = "Education"
                        },
                        new
                        {
                            ID = 3,
                            CVID = 1,
                            City = "Göteborg",
                            Description = "HLR-utbildning",
                            EndDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(38),
                            Place = "Företag1",
                            StartDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(37),
                            Title = "HLR",
                            Type = "Course"
                        },
                        new
                        {
                            ID = 4,
                            CVID = 2,
                            City = "Örebro",
                            Description = "Beskrivning blabla",
                            EndDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(42),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(41),
                            Title = "Lärarprogrammet",
                            Type = "Education"
                        },
                        new
                        {
                            ID = 5,
                            CVID = 1,
                            City = "Örebro",
                            Description = "Java",
                            EndDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(46),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 27, 8, 32, 9, 298, DateTimeKind.Local).AddTicks(44),
                            Title = "Systemvetenskap",
                            Type = "Education"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Receiver");

                    b.HasIndex("Sender");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2022, 12, 27, 8, 32, 9, 297, DateTimeKind.Local).AddTicks(8249),
                            Read = false,
                            Receiver = "användare2id",
                            Sender = "användare1id",
                            Text = "hejsan hoppsan"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLeaderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProjectLeaderID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2021, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projektbeskrivningen blabla",
                            Name = "Planeringsprojektet",
                            ProjectLeaderID = "användare1id"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2020, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projektbeskrivningen blabla",
                            Name = "Yogahemsideprojektet",
                            ProjectLeaderID = "användare2id"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projektbeskrivningen blabla",
                            Name = "CV-Projektet",
                            ProjectLeaderID = "användare3id"
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projektbeskrivningen blabla",
                            Name = "Mötesprojektet",
                            ProjectLeaderID = "användare4id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AdressID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AdressID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "användare1id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "1274ed15-73e3-472e-ad28-ee49fbd0b9c8",
                            Description = "Hejaaa",
                            Email = "inga@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Inga",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Karlsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnäringa",
                            PhoneNumber = "073-111 11 11",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "b3c280b3-da9d-4eed-b01e-43a1194310f5",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare2id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "35081f22-af71-4e85-b225-0e392b505a67",
                            Description = "Halloj",
                            Email = "gunvor@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Gunvor",
                            IsActive = true,
                            IsPublic = false,
                            LastName = "Nilsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärgunvor",
                            PhoneNumber = "073-222 22 22",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "995b9686-9490-4ffb-9041-57a71537c4f8",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare3id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "dcaca7cd-4ad6-4da1-9097-3da38edb571e",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "Jögge@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Jörgen",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Svensson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärjörgen",
                            PhoneNumber = "073-333 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "76ead78d-eb3f-409d-ad30-0c2204c909a2",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare4id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "39be6cd5-6f17-4b2d-92bf-d3fd9e46cd89",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "stenis@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Sten",
                            IsActive = true,
                            IsPublic = false,
                            LastName = "Kallesson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärsten",
                            PhoneNumber = "074-444 44 44",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "4d4ced4d-070a-41cd-b560-546d5e0d54ff",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare5id",
                            AccessFailedCount = 0,
                            AdressID = 3,
                            ConcurrencyStamp = "74b44ca9-2602-449a-9d2d-eb7e144efdf4",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "kajsa@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Kajsa",
                            IsActive = false,
                            IsPublic = true,
                            LastName = "Stenbäck",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärkajsa",
                            PhoneNumber = "075-123 55 55",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "51cceff1-33e9-4c56-9bae-64a2a55c05ba",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare6id",
                            AccessFailedCount = 0,
                            AdressID = 4,
                            ConcurrencyStamp = "33069bc3-c517-4afa-901a-45e9cfc312ff",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "frida@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Frida",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Liljedahl",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärfrida",
                            PhoneNumber = "075-555 55 55",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "5001af0f-eba0-4c2d-9520-da41722bfe63",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare7id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "7952cddf-9f94-4868-b89e-895bded8d616",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "linda@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Linda",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Nordeman",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärlinda",
                            PhoneNumber = "076-666 66 66",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "29f1f30e-c7a5-4028-974b-dd24261512ee",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare8id",
                            AccessFailedCount = 0,
                            AdressID = 3,
                            ConcurrencyStamp = "6485f44e-bc6e-4fdf-a444-81275476b349",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "lisa@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Lisa",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Kjellgren",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärlisa",
                            PhoneNumber = "077-773 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "e4254e5c-54a7-4c04-b2ae-408706d26db8",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare9id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "c1ec136f-9da4-425f-a519-fb936ee3f704",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "viktor@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Viktor",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Hemlin Gravander",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärviktor",
                            PhoneNumber = "073-333 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2021, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "f2148aed-1fd3-4ceb-8daf-33225e9176f8",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare10id",
                            AccessFailedCount = 0,
                            AdressID = 4,
                            ConcurrencyStamp = "f56f5a5d-c34b-45f1-acfb-0975e0955cd7",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "ulla@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Ulla",
                            IsActive = false,
                            IsPublic = false,
                            LastName = "Ivarsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärulla",
                            PhoneNumber = "073-888 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "010fab70-df7b-49b0-b458-65a1e8900aab",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.User_Projects", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("User_Projects");

                    b.HasData(
                        new
                        {
                            UserID = "användare1id",
                            ProjectID = 1
                        },
                        new
                        {
                            UserID = "användare1id",
                            ProjectID = 2
                        },
                        new
                        {
                            UserID = "användare2id",
                            ProjectID = 1
                        },
                        new
                        {
                            UserID = "användare2id",
                            ProjectID = 3
                        },
                        new
                        {
                            UserID = "användare3id",
                            ProjectID = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "User")
                        .WithOne("CV")
                        .HasForeignKey("CV_Projektet.Models.CV", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CV_Projektet.Models.CV_Competences", b =>
                {
                    b.HasOne("CV_Projektet.Models.CV", "CV")
                        .WithMany("CV_Competences")
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.Competence", "Competence")
                        .WithMany("CV_Competences")
                        .HasForeignKey("CompetenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("CV_Projektet.Models.Experience", b =>
                {
                    b.HasOne("CV_Projektet.Models.CV", "CV")
                        .WithMany("Experiences")
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");
                });

            modelBuilder.Entity("CV_Projektet.Models.Message", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "UserReceiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", "UserSender")
                        .WithMany("SentMessages")
                        .HasForeignKey("Sender")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "ProjectLeader")
                        .WithMany("LeadProjects")
                        .HasForeignKey("ProjectLeaderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectLeader");
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.HasOne("CV_Projektet.Models.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AdressID");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CV_Projektet.Models.User_Projects", b =>
                {
                    b.HasOne("CV_Projektet.Models.Project", "Project")
                        .WithMany("User_Project")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", "User")
                        .WithMany("UsersAndProjects")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CV_Projektet.Models.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CV_Projektet.Models.Competence", b =>
                {
                    b.Navigation("CV_Competences");
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.Navigation("CV_Competences");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.Navigation("User_Project");
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.Navigation("CV");

                    b.Navigation("LeadProjects");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("UsersAndProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
