// <auto-generated />
using System;
using CV_Projektet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV_Projektet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221226101110_testdata2")]
    partial class testdata2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CV_Projektet.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Örebro",
                            PostalCode = 12345,
                            Street = "Storgatan 1"
                        },
                        new
                        {
                            ID = 2,
                            City = "Ystad",
                            PostalCode = 12365,
                            Street = "Drottninggatan 12"
                        },
                        new
                        {
                            ID = 3,
                            City = "Göteborg",
                            PostalCode = 16845,
                            Street = "Kungsgatan 43"
                        },
                        new
                        {
                            ID = 4,
                            City = "Gnesta",
                            PostalCode = 16845,
                            Street = "Storälven 22"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Competence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Competences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "C#"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Java"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kassavana"
                        },
                        new
                        {
                            ID = 4,
                            Name = "HLR"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("TimesViewed")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("CVs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            TimesViewed = 0,
                            UserID = "användare1id"
                        },
                        new
                        {
                            ID = 2,
                            TimesViewed = 3,
                            UserID = "användare3id"
                        },
                        new
                        {
                            ID = 3,
                            TimesViewed = 12,
                            UserID = "användare2id"
                        },
                        new
                        {
                            ID = 4,
                            TimesViewed = 55,
                            UserID = "användare4id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.CV_Competences", b =>
                {
                    b.Property<int>("CVID")
                        .HasColumnType("int");

                    b.Property<int>("CompetenceID")
                        .HasColumnType("int");

                    b.HasKey("CVID", "CompetenceID");

                    b.HasIndex("CompetenceID");

                    b.ToTable("CV_Competences");

                    b.HasData(
                        new
                        {
                            CVID = 1,
                            CompetenceID = 1
                        },
                        new
                        {
                            CVID = 1,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 3
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 4
                        },
                        new
                        {
                            CVID = 3,
                            CompetenceID = 4
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 1
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 3
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Experience", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CVID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CVID");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CVID = 1,
                            City = "Lund",
                            Description = "pratade i telefon",
                            EndDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5003),
                            Place = "ICA",
                            StartDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(4996),
                            Title = "Kundtjänst",
                            Type = "Work"
                        },
                        new
                        {
                            ID = 2,
                            CVID = 1,
                            City = "Örebro",
                            Description = "Java",
                            EndDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5008),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5006),
                            Title = "Systemvetenskap",
                            Type = "Education"
                        },
                        new
                        {
                            ID = 3,
                            CVID = 1,
                            City = "Göteborg",
                            Description = "HLR-utbildning",
                            EndDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5012),
                            Place = "Företag1",
                            StartDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5011),
                            Title = "HLR",
                            Type = "Course"
                        },
                        new
                        {
                            ID = 4,
                            CVID = 2,
                            City = "Örebro",
                            Description = "Beskrivning blabla",
                            EndDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5016),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5015),
                            Title = "Lärarprogrammet",
                            Type = "Education"
                        },
                        new
                        {
                            ID = 5,
                            CVID = 1,
                            City = "Örebro",
                            Description = "Java",
                            EndDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5020),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(5019),
                            Title = "Systemvetenskap",
                            Type = "Education"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Receiver");

                    b.HasIndex("Sender");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2022, 12, 26, 11, 11, 10, 75, DateTimeKind.Local).AddTicks(3218),
                            Read = false,
                            Receiver = "användare2id",
                            Sender = "användare1id",
                            Text = "hejsan hoppsan"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLeaderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProjectLeaderID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Projektbeskrivningen blabla",
                            Name = "Planeringsprojektet",
                            ProjectLeaderID = "användare1id"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Projektbeskrivningen blabla",
                            Name = "Yogahemsideprojektet",
                            ProjectLeaderID = "användare2id"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Projektbeskrivningen blabla",
                            Name = "CV-Projektet",
                            ProjectLeaderID = "användare3id"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Projektbeskrivningen blabla",
                            Name = "Mötesprojektet",
                            ProjectLeaderID = "användare4id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AdressID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AdressID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "användare1id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "5de2af1e-2646-490a-93f2-db12544c1b4b",
                            Description = "Hejaaa",
                            Email = "inga@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Inga",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Karlsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnäringa",
                            PhoneNumber = "073-111 11 11",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "e8d8aa20-4b12-4a6f-9813-01bececcc3e9",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare2id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "6ce4b970-a70f-4fa2-a1c9-e01d7872891a",
                            Description = "Halloj",
                            Email = "gunvor@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Gunvor",
                            IsActive = true,
                            IsPublic = false,
                            LastName = "Nilsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärgunvor",
                            PhoneNumber = "073-222 22 22",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "fe40f184-c75f-4f7f-91cd-707873787263",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare3id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "1f219210-0ec0-437e-ad67-d720e75c9588",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "Jögge@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Jörgen",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Svensson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärjörgen",
                            PhoneNumber = "073-333 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "9fca94df-e68a-4ef6-8cc9-2897c99fde58",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare4id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "c42ddf65-d100-4776-9c59-8d8306fc12d6",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "stenis@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Sten",
                            IsActive = true,
                            IsPublic = false,
                            LastName = "Kallesson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärsten",
                            PhoneNumber = "074-444 44 44",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "f74088d1-aa8c-4394-8e02-aebe1140bb64",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare5id",
                            AccessFailedCount = 0,
                            AdressID = 3,
                            ConcurrencyStamp = "a8db9ea6-6181-44a2-aad5-dab92c1073e2",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "kajsa@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Kajsa",
                            IsActive = false,
                            IsPublic = true,
                            LastName = "Stenbäck",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärkajsa",
                            PhoneNumber = "075-123 55 55",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "f5d51b7d-b23e-4203-9c72-f1f1afff4497",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare6id",
                            AccessFailedCount = 0,
                            AdressID = 4,
                            ConcurrencyStamp = "46f4af0c-1ea6-4167-8af7-c0c850cab21e",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "frida@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Frida",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Liljedahl",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärfrida",
                            PhoneNumber = "075-555 55 55",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "b9d1f008-bf4b-40ed-b6b7-56ead3aae65f",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare7id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "ae18cc11-da5a-4aee-a80b-386dcaa6fa55",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "linda@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Linda",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Nordeman",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärlinda",
                            PhoneNumber = "076-666 66 66",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "ff1adacc-c79d-410e-8e27-06235a9adfef",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare8id",
                            AccessFailedCount = 0,
                            AdressID = 3,
                            ConcurrencyStamp = "3d360315-b771-48f1-808e-d3591ce1e49d",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "lisa@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Lisa",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Kjellgren",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärlisa",
                            PhoneNumber = "077-773 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "ad19adce-0b1b-487f-9ab1-d1c91bf8b0d7",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare9id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "ce5bdfd7-b21c-4462-879c-982fe9554395",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "viktor@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Viktor",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Hemlin Gravander",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärviktor",
                            PhoneNumber = "073-333 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2021, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "af0a6b89-2a97-4804-9085-36328e67a737",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare10id",
                            AccessFailedCount = 0,
                            AdressID = 4,
                            ConcurrencyStamp = "747b73d2-5a22-4bab-b75e-6269cad511a7",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "ulla@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Ulla",
                            IsActive = false,
                            IsPublic = false,
                            LastName = "Ivarsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärulla",
                            PhoneNumber = "073-888 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "21341959-07fb-422a-9855-23d0b0e1c266",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.User_Projects", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("User_Projects");

                    b.HasData(
                        new
                        {
                            UserID = "användare1id",
                            ProjectID = 1
                        },
                        new
                        {
                            UserID = "användare1id",
                            ProjectID = 2
                        },
                        new
                        {
                            UserID = "användare2id",
                            ProjectID = 1
                        },
                        new
                        {
                            UserID = "användare2id",
                            ProjectID = 3
                        },
                        new
                        {
                            UserID = "användare3id",
                            ProjectID = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "User")
                        .WithOne("CV")
                        .HasForeignKey("CV_Projektet.Models.CV", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CV_Projektet.Models.CV_Competences", b =>
                {
                    b.HasOne("CV_Projektet.Models.CV", "CV")
                        .WithMany("CV_Competences")
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.Competence", "Competence")
                        .WithMany("CV_Competences")
                        .HasForeignKey("CompetenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("CV_Projektet.Models.Experience", b =>
                {
                    b.HasOne("CV_Projektet.Models.CV", "CV")
                        .WithMany("Experiences")
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");
                });

            modelBuilder.Entity("CV_Projektet.Models.Message", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "UserReceiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", "UserSender")
                        .WithMany("SentMessages")
                        .HasForeignKey("Sender")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "ProjectLeader")
                        .WithMany("LeadProjects")
                        .HasForeignKey("ProjectLeaderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectLeader");
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.HasOne("CV_Projektet.Models.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AdressID");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CV_Projektet.Models.User_Projects", b =>
                {
                    b.HasOne("CV_Projektet.Models.Project", "Project")
                        .WithMany("User_Project")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", "User")
                        .WithMany("UsersAndProjects")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CV_Projektet.Models.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CV_Projektet.Models.Competence", b =>
                {
                    b.Navigation("CV_Competences");
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.Navigation("CV_Competences");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.Navigation("User_Project");
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.Navigation("CV");

                    b.Navigation("LeadProjects");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("UsersAndProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
