// <auto-generated />
using System;
using CV_Projektet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV_Projektet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CV_Projektet.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            City = "Örebro",
                            PostalCode = 12345,
                            Street = "Storgatan 1"
                        },
                        new
                        {
                            ID = 2,
                            City = "Ystad",
                            PostalCode = 12365,
                            Street = "Drottninggatan 12"
                        },
                        new
                        {
                            ID = 3,
                            City = "Göteborg",
                            PostalCode = 16845,
                            Street = "Kungsgatan 43"
                        },
                        new
                        {
                            ID = 4,
                            City = "Gnesta",
                            PostalCode = 16845,
                            Street = "Storälven 22"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Competence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Competences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "C#"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Java"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Kassavana"
                        },
                        new
                        {
                            ID = 4,
                            Name = "HLR"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("TimesViewed")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("CVs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            TimesViewed = 0,
                            UserID = "användare1id"
                        },
                        new
                        {
                            ID = 2,
                            TimesViewed = 3,
                            UserID = "användare3id"
                        },
                        new
                        {
                            ID = 3,
                            TimesViewed = 12,
                            UserID = "användare2id"
                        },
                        new
                        {
                            ID = 4,
                            TimesViewed = 55,
                            UserID = "användare4id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.CV_Competences", b =>
                {
                    b.Property<int>("CVID")
                        .HasColumnType("int");

                    b.Property<int>("CompetenceID")
                        .HasColumnType("int");

                    b.HasKey("CVID", "CompetenceID");

                    b.HasIndex("CompetenceID");

                    b.ToTable("CV_Competences");

                    b.HasData(
                        new
                        {
                            CVID = 1,
                            CompetenceID = 1
                        },
                        new
                        {
                            CVID = 1,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 3
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 2,
                            CompetenceID = 4
                        },
                        new
                        {
                            CVID = 3,
                            CompetenceID = 4
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 1
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 2
                        },
                        new
                        {
                            CVID = 4,
                            CompetenceID = 3
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Experience", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CVID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CVID");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CVID = 1,
                            City = "Lund",
                            Description = "pratade i telefon",
                            EndDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6585),
                            Place = "ICA",
                            StartDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6567),
                            Title = "Kundtjänst",
                            Type = "Work"
                        },
                        new
                        {
                            ID = 2,
                            CVID = 1,
                            City = "Örebro",
                            Description = "Java",
                            EndDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6593),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6590),
                            Title = "Systemvetenskap",
                            Type = "Education"
                        },
                        new
                        {
                            ID = 3,
                            CVID = 1,
                            City = "Göteborg",
                            Description = "HLR-utbildning",
                            EndDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6598),
                            Place = "Företag1",
                            StartDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6596),
                            Title = "HLR",
                            Type = "Course"
                        },
                        new
                        {
                            ID = 4,
                            CVID = 2,
                            City = "Örebro",
                            Description = "Beskrivning blabla",
                            EndDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6603),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6601),
                            Title = "Lärarprogrammet",
                            Type = "Education"
                        },
                        new
                        {
                            ID = 5,
                            CVID = 1,
                            City = "Örebro",
                            Description = "Java",
                            EndDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6609),
                            Place = "Örebro Universitet",
                            StartDate = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(6607),
                            Title = "Systemvetenskap",
                            Type = "Education"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.ImageModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ID = 4,
                            Name = "image (1)223847664.png",
                            Title = "Profilbild",
                            UserID = "användare1id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Receiver");

                    b.HasIndex("Sender");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2022, 12, 26, 22, 4, 18, 124, DateTimeKind.Local).AddTicks(3224),
                            Read = false,
                            Receiver = "användare2id",
                            Sender = "användare1id",
                            Text = "hejsan hoppsan"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLeaderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ProjectLeaderID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Projektbeskrivningen blabla",
                            Name = "Planeringsprojektet",
                            ProjectLeaderID = "användare1id"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Projektbeskrivningen blabla",
                            Name = "Yogahemsideprojektet",
                            ProjectLeaderID = "användare2id"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Projektbeskrivningen blabla",
                            Name = "CV-Projektet",
                            ProjectLeaderID = "användare3id"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Projektbeskrivningen blabla",
                            Name = "Mötesprojektet",
                            ProjectLeaderID = "användare4id"
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AdressID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AdressID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "användare1id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "416128f7-aeb7-4d60-8022-5fe0b8e5b64a",
                            Description = "Hejaaa",
                            Email = "inga@hotmail.com",
                            EmailConfirmed = false,
                            FirstName = "Inga",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Karlsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnäringa",
                            PhoneNumber = "073-111 11 11",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "23a4e9cd-48c4-4511-86d9-da604bd2b883",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare2id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "8e0d5e6d-36c1-49a8-bdca-f618ec23c0f8",
                            Description = "Halloj",
                            Email = "gunvor@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Gunvor",
                            IsActive = true,
                            IsPublic = false,
                            LastName = "Nilsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärgunvor",
                            PhoneNumber = "073-222 22 22",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c3cd04d3-2901-418e-ba3c-6b6d9e952965",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare3id",
                            AccessFailedCount = 0,
                            AdressID = 1,
                            ConcurrencyStamp = "3d7ba274-1ae2-4cd8-ab10-235a6c32903c",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "Jögge@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Jörgen",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Svensson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärjörgen",
                            PhoneNumber = "073-333 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "9277c05d-9ac7-4273-a1b3-928c7865b998",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare4id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "f4511cd7-02f6-4a15-927b-a57748c01141",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "stenis@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Sten",
                            IsActive = true,
                            IsPublic = false,
                            LastName = "Kallesson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärsten",
                            PhoneNumber = "074-444 44 44",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "f68afdff-05ce-4f6f-a408-1b20f0070c0e",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare5id",
                            AccessFailedCount = 0,
                            AdressID = 3,
                            ConcurrencyStamp = "336c3f59-a1ad-4d63-b240-d61265b62c37",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "kajsa@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Kajsa",
                            IsActive = false,
                            IsPublic = true,
                            LastName = "Stenbäck",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärkajsa",
                            PhoneNumber = "075-123 55 55",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "36f467c0-2128-4bbb-88ed-53d4af5d9022",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare6id",
                            AccessFailedCount = 0,
                            AdressID = 4,
                            ConcurrencyStamp = "333b2692-3b9d-4db9-9a63-8cbb551bda31",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "frida@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Frida",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Liljedahl",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärfrida",
                            PhoneNumber = "075-555 55 55",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "90f217bd-5cfa-43d1-8ea0-71276883f549",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare7id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "4ce0a7ea-9693-4abe-8c98-030f27102a83",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "linda@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Linda",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Nordeman",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärlinda",
                            PhoneNumber = "076-666 66 66",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "e23b5b58-d339-4660-8a29-80636ef45117",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare8id",
                            AccessFailedCount = 0,
                            AdressID = 3,
                            ConcurrencyStamp = "33e462c5-52f8-44e8-a4ff-263f1f84c12d",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "lisa@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Lisa",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Kjellgren",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärlisa",
                            PhoneNumber = "077-773 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2022, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "4c5a13cd-bc6a-4d8c-9ba8-8c66c059ed08",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare9id",
                            AccessFailedCount = 0,
                            AdressID = 2,
                            ConcurrencyStamp = "5f1b0431-ecea-4fa0-908c-872c1cde3066",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "viktor@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Viktor",
                            IsActive = true,
                            IsPublic = true,
                            LastName = "Hemlin Gravander",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärviktor",
                            PhoneNumber = "073-333 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2021, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "8c771ce8-4ed9-4b80-9341-3bf00c35bb06",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "användare10id",
                            AccessFailedCount = 0,
                            AdressID = 4,
                            ConcurrencyStamp = "78bbd489-6ebe-4359-aca0-efa066bde72c",
                            Description = "dfggdffdgfdgdffdggdf",
                            Email = "ulla@hotmail.se",
                            EmailConfirmed = false,
                            FirstName = "Ulla",
                            IsActive = false,
                            IsPublic = false,
                            LastName = "Ivarsson",
                            LockoutEnabled = false,
                            PasswordHash = "mittnamnärulla",
                            PhoneNumber = "073-888 33 33",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c516b162-3e4a-4cbe-99db-14909b30b839",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("CV_Projektet.Models.User_Projects", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("User_Projects");

                    b.HasData(
                        new
                        {
                            UserID = "användare1id",
                            ProjectID = 1
                        },
                        new
                        {
                            UserID = "användare1id",
                            ProjectID = 2
                        },
                        new
                        {
                            UserID = "användare2id",
                            ProjectID = 1
                        },
                        new
                        {
                            UserID = "användare2id",
                            ProjectID = 3
                        },
                        new
                        {
                            UserID = "användare3id",
                            ProjectID = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "User")
                        .WithOne("CV")
                        .HasForeignKey("CV_Projektet.Models.CV", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CV_Projektet.Models.CV_Competences", b =>
                {
                    b.HasOne("CV_Projektet.Models.CV", "CV")
                        .WithMany("CV_Competences")
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.Competence", "Competence")
                        .WithMany("CV_Competences")
                        .HasForeignKey("CompetenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("CV_Projektet.Models.Experience", b =>
                {
                    b.HasOne("CV_Projektet.Models.CV", "CV")
                        .WithMany("Experiences")
                        .HasForeignKey("CVID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CV");
                });

            modelBuilder.Entity("CV_Projektet.Models.ImageModel", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "user")
                        .WithOne("imageModel")
                        .HasForeignKey("CV_Projektet.Models.ImageModel", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("CV_Projektet.Models.Message", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "UserReceiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("Receiver")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", "UserSender")
                        .WithMany("SentMessages")
                        .HasForeignKey("Sender")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", "ProjectLeader")
                        .WithMany("LeadProjects")
                        .HasForeignKey("ProjectLeaderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectLeader");
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.HasOne("CV_Projektet.Models.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AdressID");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CV_Projektet.Models.User_Projects", b =>
                {
                    b.HasOne("CV_Projektet.Models.Project", "Project")
                        .WithMany("User_Project")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", "User")
                        .WithMany("UsersAndProjects")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CV_Projektet.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CV_Projektet.Models.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CV_Projektet.Models.Competence", b =>
                {
                    b.Navigation("CV_Competences");
                });

            modelBuilder.Entity("CV_Projektet.Models.CV", b =>
                {
                    b.Navigation("CV_Competences");

                    b.Navigation("Experiences");
                });

            modelBuilder.Entity("CV_Projektet.Models.Project", b =>
                {
                    b.Navigation("User_Project");
                });

            modelBuilder.Entity("CV_Projektet.Models.User", b =>
                {
                    b.Navigation("CV");

                    b.Navigation("LeadProjects");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");

                    b.Navigation("UsersAndProjects");

                    b.Navigation("imageModel");
                });
#pragma warning restore 612, 618
        }
    }
}
